/* Extracted product & contract management tables */

CREATE TABLE IF NOT EXISTS `xdyai_productinfo` (
  `id` bigint NOT NULL COMMENT '主键',
  `created_time` datetime NULL COMMENT '创建时间',
  `updated_time` datetime NULL COMMENT '更新时间',
  `created_by` varchar(255) NULL COMMENT '创建者',
  `updated_by` varchar(255) NULL COMMENT '更新者',
  `code` varchar(50) NULL COMMENT '存货编码',
  `name` varchar(200) NULL COMMENT '存货名称',
  `shorthand` varchar(200) NULL COMMENT '助记码',
  `specification` varchar(200) NULL COMMENT '规格型号',
  `value_type` varchar(50) NULL COMMENT '(枚举)计价方式',
  `inventory_class` varchar(30) NULL COMMENT '所属类别编码',
  `inventory_class_name` varchar(100) NULL COMMENT '所属类别',
  `tas_rate` varchar(100) NULL COMMENT '(枚举)税率%',
  `is_new` tinyint(1) NULL COMMENT '(01)新品',
  `disabled` tinyint(1) NULL COMMENT '(01)停用',
  `unit_group` varchar(100) NULL COMMENT '计量单位组',
  `main_unit` varchar(50) NULL COMMENT '主计量',
  `change_type` varchar(100) NULL COMMENT '(枚举)换算类型',
  `unit1` varchar(50) NULL COMMENT '辅计量1',
  `change_rate1` decimal(31,8) NULL COMMENT '辅1换算率',
  `sub_unit_by_report` varchar(100) NULL COMMENT '报表辅单位',
  `unit_by_stock` varchar(100) NULL COMMENT '库存常用单位',
  `unit_by_purchase` varchar(100) NULL COMMENT '采购常用单位',
  `unit_by_sale` varchar(100) NULL COMMENT '销售常用单位',
  `unit_by_manufacture` varchar(100) NULL COMMENT '生产常用单位',
  `is_purchase` tinyint(1) NULL COMMENT '(01)外购',
  `is_sale` tinyint(1) NULL COMMENT '(01)销售',
  `is_made_self` tinyint(1) NULL COMMENT '(01)自制',
  `is_material` tinyint(1) NULL COMMENT '(01)生产耗用',
  `is_labor_cost` tinyint(1) NULL COMMENT '(01)劳务费用',
  `is_eshop` tinyint(1) NULL COMMENT '(01)电商',
  `back_flush_material` tinyint(1) NULL COMMENT '(01)倒冲料',
  `product_info` varchar(100) NULL COMMENT '品牌',
  `new_product_period` varchar(50) NULL COMMENT '新品周期(天)',
  `jin_shui_code` varchar(19) NULL COMMENT '金税税收分类编码',
  `unit2` varchar(50) NULL COMMENT '辅计量2',
  `change_rate2` decimal(31,8) NULL COMMENT '辅2换算率',
  `inventory_descript` varchar(100) NULL COMMENT '存货描述',
  `inv_s_cost` decimal(31,2) NULL COMMENT '参考成本',
  `low_quantity` decimal(31,2) NULL COMMENT '最低库存',
  `top_quantity` decimal(31,2) NULL COMMENT '最高库存',
  `safe_quantity` decimal(31,2) NULL COMMENT '安全库存',
  `standard_turnover_days` decimal(31,4) NULL COMMENT '标准周转天数',
  `partner` varchar(50) NULL COMMENT '默认供应商编码',
  `warehouse_warehouse_name` varchar(100) NULL COMMENT '默认仓库',
  `procure_batch` decimal(31,2) NULL COMMENT '采购批量',
  `pick_batch` decimal(31,2) NULL COMMENT '领料批量',
  `pick_batch_method` varchar(100) NULL COMMENT '领料批量处理方式',
  `in_storage_up_limit` decimal(31,4) NULL COMMENT '入库上限比例%',
  `out_storage_up_limit` decimal(31,4) NULL COMMENT '出库上限比例%',
  `working_hours` decimal(31,4) NULL COMMENT '标准工时-主计量',
  `purchase_price_formula` varchar(100) NULL COMMENT '采购价',
  `retail_price_new` decimal(31,2) NULL COMMENT '零售价',
  `retail_price_formula` varchar(100) NULL COMMENT '普通客户价',
  `inv_s_cost1_formula` varchar(100) NULL COMMENT '一级批发价',
  `inv_s_cost2_formula` varchar(100) NULL COMMENT '二级批发价',
  `inv_s_cost3_formula` varchar(100) NULL COMMENT '三级批发价',
  `inv_l_s_price_formula` varchar(100) NULL COMMENT '最低售价',
  `inv_m_p_cost_formula` varchar(100) NULL COMMENT '最高进价',
  `markup_rate` decimal(31,4) NULL COMMENT '加价率%',
  `discount` decimal(31,4) NULL COMMENT '扣率%',
  `remarks` varchar(100) NULL COMMENT '备注',
  `warehouse` varchar(30) NULL COMMENT '默认仓库编码',
  `partner_name` varchar(100) NULL COMMENT '默认供应商',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_productinfo_code` (`code`)
) COMMENT='商品信息表' ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `xdyai_productversion` (
  `id` bigint NOT NULL COMMENT '主键',
  `created_time` datetime NULL COMMENT '创建时间',
  `updated_time` datetime NULL COMMENT '更新时间',
  `created_by` varchar(255) NULL COMMENT '创建者',
  `updated_by` varchar(255) NULL COMMENT '更新者',
  `version_name` varchar(255) NULL COMMENT '版本名称',
  `module_ids` varchar(4000) NULL COMMENT '功能模块',
  `version_order` bigint NULL DEFAULT 1 COMMENT '版本排序',
  `version_status` varchar(255) NULL DEFAULT 1 COMMENT '版本状态',
  `description` varchar(255) NULL COMMENT '版本简介',
  `default_account_num` bigint NULL DEFAULT 0 COMMENT '默认账套数',
  `one_account_price` bigint NULL DEFAULT 0 COMMENT '每增加1账套收费',
  `account_max_num` bigint NULL DEFAULT 0 COMMENT '上限数量',
  `default_p_c_user_num` bigint NULL DEFAULT 0 COMMENT '默认用户数',
  `pc_user_price_under_ten` bigint NULL DEFAULT 0 COMMENT '不超过10用户，每增加1用户收费',
  `pc_user_price_on_ten` bigint NULL DEFAULT 0 COMMENT '超过10户，每增加1用户收费',
  `p_c_user_max` bigint NULL DEFAULT 0 COMMENT '上限数量',
  `default_move_user_num` bigint NULL DEFAULT 0 COMMENT '默认用户数',
  `move_user_price_under_ten` bigint NULL DEFAULT 0 COMMENT '不超过10用户，每增加2用户收费',
  `move_user_price_on_ten` bigint NULL DEFAULT 0 COMMENT '超过10用户，每增加2用户收费',
  `move_user_max` bigint NULL DEFAULT 0 COMMENT '上限数量',
  `year_max` bigint NULL DEFAULT 1 COMMENT '最多可选',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_productversion_version_name` (`version_name`)
) COMMENT='版本管理表' ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `xdyai_functionalmodule` (
  `id` bigint NOT NULL COMMENT '主键',
  `created_time` datetime NULL COMMENT '创建时间',
  `updated_time` datetime NULL COMMENT '更新时间',
  `created_by` varchar(255) NULL COMMENT '创建者',
  `updated_by` varchar(255) NULL COMMENT '更新者',
  `name` varchar(255) NULL COMMENT '模块名称',
  `depend_module` varchar(255) NULL COMMENT '依赖模块',
  `exclusion_module` varchar(255) NULL COMMENT '互斥模块',
  `parent_module` bigint NULL DEFAULT 0 COMMENT '上级模块',
  `order` bigint NULL DEFAULT 1 COMMENT '模块排序',
  `status` varchar(255) NULL DEFAULT 1 COMMENT '模块状态',
  `description` varchar(255) NULL COMMENT '模块备注',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_functionalmodule_name` (`name`)
) COMMENT='功能模块表' ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `xdyai_productfunctionrelationship` (
  `id` bigint NOT NULL COMMENT '主键',
  `created_time` datetime NULL COMMENT '创建时间',
  `updated_time` datetime NULL COMMENT '更新时间',
  `created_by` varchar(255) NULL COMMENT '创建者',
  `updated_by` varchar(255) NULL COMMENT '更新者',
  `module_id` bigint NULL COMMENT '模块ID',
  `version_id` bigint NULL COMMENT '版本ID',
  `price` bigint NULL DEFAULT 0 COMMENT '基础价',
  `unit` varchar(255) NULL DEFAULT '年' COMMENT '单位名称',
  `defined_num` tinyint(1) NULL DEFAULT 0 COMMENT '自定义数量',
  `start_num` bigint NULL DEFAULT 0 COMMENT '起始数量',
  `step_num` bigint NULL DEFAULT 0 COMMENT '递进数量',
  `step_price` bigint NULL DEFAULT 0 COMMENT '递进价格',
  `max_num` bigint NULL DEFAULT 0 COMMENT '上限数量',
  `describe` varchar(255) NULL DEFAULT '无' COMMENT '业务描述',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_productfunctionrelationship_module_version` (`module_id`, `version_id`)
) COMMENT='功能版本中间表' ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `xdyai_contract` (
  `id` bigint NOT NULL COMMENT '主键',
  `created_time` datetime NULL COMMENT '创建时间',
  `updated_time` datetime NULL COMMENT '更新时间',
  `created_by` varchar(255) NULL COMMENT '创建者',
  `updated_by` varchar(255) NULL COMMENT '更新者',
  `name` varchar(255) NOT NULL COMMENT '合同名称',
  `initiator` varchar(255) NOT NULL DEFAULT '北京星蝶云科技有限公司' COMMENT '合同发起方(主体)',
  `customer` bigint NOT NULL COMMENT '客户',
  `status` varchar(255) NOT NULL DEFAULT 1 COMMENT '状态',
  `initiation_time` datetime NOT NULL COMMENT '发起时间',
  `deadline` datetime NOT NULL COMMENT '截止时间',
  `cus_people` varchar(255) NOT NULL COMMENT '客户联系人',
  `cus_phone` varchar(255) NOT NULL COMMENT '客户电话',
  `order_type` varchar(255) NOT NULL COMMENT '订单类型',
  `cus_name` varchar(255) NOT NULL COMMENT '客户名称',
  `cus_address` varchar(255) NOT NULL COMMENT '客户地址',
  `cus_postal` varchar(255) NOT NULL COMMENT '客户邮编',
  `cus_email` varchar(255) NOT NULL COMMENT '客户邮箱',
  `num` varchar(255) NOT NULL COMMENT '合同编号',
  `signdate` date NOT NULL COMMENT '签约日期',
  `ordernum` varchar(255) NOT NULL COMMENT '订单编号',
  `type` varchar(255) NOT NULL COMMENT '服务类型',
  `originalprice` decimal(31,2) NOT NULL COMMENT '产品原价',
  `discount` decimal(31,2) NOT NULL COMMENT '优惠金额',
  `pay_type` varchar(255) NOT NULL COMMENT '付款方式',
  `bank_account` varchar(255) NOT NULL COMMENT '我方银行账号',
  `bankofdeposit` varchar(255) NOT NULL COMMENT '我方开户行',
  `total_amount` decimal(31,2) NOT NULL COMMENT '合计金额',
  `big_amount` varchar(255) NOT NULL COMMENT '大写总金额',
  `version` varchar(255) NOT NULL COMMENT '产品版本',
  `application_module` varchar(4000) NOT NULL COMMENT '应用模块',
  `sign_order` bigint NULL COMMENT '签约方式',
  `document_preview` varchar(4000) NULL COMMENT '文档预览地址',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_contract_num` (`num`),
  UNIQUE KEY `uk_contract_ordernum` (`ordernum`)
) COMMENT='合同表' ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `xdyai_contract_billing_term` (
  `id` bigint NOT NULL COMMENT '主键',
  `created_time` datetime NULL COMMENT '创建时间',
  `updated_time` datetime NULL COMMENT '更新时间',
  `created_by` varchar(255) NULL COMMENT '创建者',
  `updated_by` varchar(255) NULL COMMENT '更新者',
  `contract_id` bigint NOT NULL COMMENT '合同ID',
  `term_name` varchar(255) NULL COMMENT '条款名称',
  `trigger_event` bigint NULL COMMENT '触发事件枚举',
  `percentage` decimal(31,2) NULL COMMENT '比例',
  `amount` decimal(31,2) NULL COMMENT '金额',
  `due_date` date NULL COMMENT '应收日期',
  `status` bigint NULL COMMENT '状态',
  `sequence` int NULL COMMENT '顺序号',
  `remark` varchar(4000) NULL COMMENT '备注',
  PRIMARY KEY (`id`)
) COMMENT='合同收款条款表' ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `xdyai_quote` (
  `id` bigint NOT NULL COMMENT '主键',
  `created_time` datetime NULL COMMENT '创建时间',
  `updated_time` datetime NULL COMMENT '更新时间',
  `created_by` varchar(255) NULL COMMENT '创建者',
  `updated_by` varchar(255) NULL COMMENT '更新者',
  `customer_id` bigint NOT NULL COMMENT '客户ID',
  `opportunity_id` bigint NULL COMMENT '商机ID',
  `quote_no` varchar(255) NULL COMMENT '报价单号',
  `amount` decimal(31,2) NULL COMMENT '报价金额',
  `status` bigint NULL COMMENT '报价状态',
  `remark` varchar(4000) NULL COMMENT '备注',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_quote_quote_no` (`quote_no`)
) COMMENT='报价表' ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `xdyai_quote_item` (
  `id` bigint NOT NULL COMMENT '主键',
  `created_time` datetime NULL COMMENT '创建时间',
  `updated_time` datetime NULL COMMENT '更新时间',
  `created_by` varchar(255) NULL COMMENT '创建者',
  `updated_by` varchar(255) NULL COMMENT '更新者',
  `quote_id` bigint NOT NULL COMMENT '报价ID',
  `product_id` bigint NULL COMMENT '产品ID',
  `quantity` decimal(31,2) NULL COMMENT '数量',
  `unit_price` decimal(31,2) NULL COMMENT '单价',
  `amount` decimal(31,2) NULL COMMENT '金额',
  `remark` varchar(255) NULL COMMENT '备注',
  PRIMARY KEY (`id`)
) COMMENT='报价明细表' ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `xdyai_invoice_notice` (
  `id` bigint NOT NULL COMMENT '主键',
  `created_time` datetime NULL COMMENT '创建时间',
  `updated_time` datetime NULL COMMENT '更新时间',
  `created_by` varchar(255) NULL COMMENT '创建者',
  `updated_by` varchar(255) NULL COMMENT '更新者',
  `contract_id` bigint NULL COMMENT '合同ID',
  `project_id` bigint NULL COMMENT '项目ID',
  `trigger_source` bigint NULL COMMENT '触发来源',
  `billing_term_id` bigint NULL COMMENT '收款条款ID',
  `amount` decimal(31,2) NULL COMMENT '应开金额',
  `tax_rate_version_id` bigint NULL COMMENT '税率版本ID',
  `due_date` date NULL COMMENT '应开日期',
  `status` bigint NULL COMMENT '状态',
  PRIMARY KEY (`id`)
) COMMENT='开票预警表' ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `xdyai_invoice` (
  `id` bigint NOT NULL COMMENT '主键',
  `created_time` datetime NULL COMMENT '创建时间',
  `updated_time` datetime NULL COMMENT '更新时间',
  `created_by` varchar(255) NULL COMMENT '创建者',
  `updated_by` varchar(255) NULL COMMENT '更新者',
  `invoice_no` varchar(255) NULL COMMENT '发票号',
  `customer_id` bigint NULL COMMENT '客户ID',
  `contract_id` bigint NULL COMMENT '合同ID',
  `project_id` bigint NULL COMMENT '项目ID',
  `billing_entity_id` bigint NULL COMMENT '开票主体ID',
  `amount` decimal(31,2) NULL COMMENT '含税金额',
  `tax_rate_version_id` bigint NULL COMMENT '税率版本ID',
  `tax_amount` decimal(31,2) NULL COMMENT '税额',
  `issue_date` date NULL COMMENT '开票日期',
  `invoice_type` varchar(255) NULL COMMENT '发票类型',
  `bank_account_id` bigint NULL COMMENT '收款账户ID',
  `file_id` bigint NULL COMMENT '发票附件ID',
  `status` bigint NULL COMMENT '状态',
  `remark` varchar(4000) NULL COMMENT '备注',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_invoice_invoice_no` (`invoice_no`)
) COMMENT='发票表' ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `xdyai_receipt` (
  `id` bigint NOT NULL COMMENT '主键',
  `created_time` datetime NULL COMMENT '创建时间',
  `updated_time` datetime NULL COMMENT '更新时间',
  `created_by` varchar(255) NULL COMMENT '创建者',
  `updated_by` varchar(255) NULL COMMENT '更新者',
  `receipt_no` varchar(255) NULL COMMENT '回款单号',
  `customer_id` bigint NULL COMMENT '客户ID',
  `contract_id` bigint NULL COMMENT '合同ID',
  `amount` decimal(31,2) NULL COMMENT '到账金额',
  `received_date` date NULL COMMENT '到账日期',
  `bank_account_id` bigint NULL COMMENT '收款账户ID',
  `status` bigint NULL COMMENT '状态',
  `recognized_by` varchar(255) NULL COMMENT '认领人',
  `recognized_time` datetime NULL COMMENT '认领时间',
  `remark` varchar(4000) NULL COMMENT '备注',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_receipt_receipt_no` (`receipt_no`)
) COMMENT='回款表' ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `xdyai_receipt_exception` (
  `id` bigint NOT NULL COMMENT '主键',
  `created_time` datetime NULL COMMENT '创建时间',
  `updated_time` datetime NULL COMMENT '更新时间',
  `created_by` varchar(255) NULL COMMENT '创建者',
  `updated_by` varchar(255) NULL COMMENT '更新者',
  `receipt_id` bigint NOT NULL COMMENT '回款ID',
  `reason` varchar(4000) NULL COMMENT '异常原因',
  `status` bigint NULL COMMENT '处理状态',
  `resolved_by` varchar(255) NULL COMMENT '处理人',
  `resolved_time` datetime NULL COMMENT '处理时间',
  `remark` varchar(4000) NULL COMMENT '备注',
  PRIMARY KEY (`id`)
) COMMENT='回款异常认领表' ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `xdyai_payment` (
  `id` bigint NOT NULL COMMENT '主键',
  `created_time` datetime NULL COMMENT '创建时间',
  `updated_time` datetime NULL COMMENT '更新时间',
  `created_by` varchar(255) NULL COMMENT '创建者',
  `updated_by` varchar(255) NULL COMMENT '更新者',
  `payee_name` varchar(255) NULL COMMENT '收款方名称',
  `amount` decimal(31,2) NULL COMMENT '付款金额',
  `pay_date` date NULL COMMENT '付款日期',
  `bank_account_id` bigint NULL COMMENT '付款账户ID',
  `status` bigint NULL COMMENT '状态',
  `remark` varchar(4000) NULL COMMENT '备注',
  PRIMARY KEY (`id`)
) COMMENT='付款表' ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `xdyai_org_entity` (
  `id` bigint NOT NULL COMMENT '主键',
  `created_time` datetime NULL COMMENT '创建时间',
  `updated_time` datetime NULL COMMENT '更新时间',
  `created_by` varchar(255) NULL COMMENT '创建者',
  `updated_by` varchar(255) NULL COMMENT '更新者',
  `name` varchar(255) NOT NULL COMMENT '主体名称',
  `tax_no` varchar(64) NULL COMMENT '税号',
  `region` varchar(255) NULL COMMENT '地区',
  `status` bigint NULL COMMENT '状态',
  `default_bank_account_id` bigint NULL COMMENT '默认银行账户ID',
  `remark` varchar(4000) NULL COMMENT '备注',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_org_entity_tax_no` (`tax_no`)
) COMMENT='组织结算主体表' ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `xdyai_bank_account` (
  `id` bigint NOT NULL COMMENT '主键',
  `created_time` datetime NULL COMMENT '创建时间',
  `updated_time` datetime NULL COMMENT '更新时间',
  `created_by` varchar(255) NULL COMMENT '创建者',
  `updated_by` varchar(255) NULL COMMENT '更新者',
  `owner_type` varchar(64) NULL COMMENT '账户归属类型',
  `owner_id` bigint NULL COMMENT '账户归属ID',
  `bank_name` varchar(255) NULL COMMENT '开户行',
  `account_name` varchar(255) NULL COMMENT '户名',
  `account_no` varchar(255) NULL COMMENT '账号',
  `status` bigint NULL COMMENT '状态',
  `remark` varchar(4000) NULL COMMENT '备注',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_bank_account_owner` (`owner_type`, `owner_id`, `account_no`)
) COMMENT='银行账户表' ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `xdyai_bank_route_rule` (
  `id` bigint NOT NULL COMMENT '主键',
  `created_time` datetime NULL COMMENT '创建时间',
  `updated_time` datetime NULL COMMENT '更新时间',
  `created_by` varchar(255) NULL COMMENT '创建者',
  `updated_by` varchar(255) NULL COMMENT '更新者',
  `org_entity_id` bigint NULL COMMENT '结算主体ID',
  `bank_account_id` bigint NULL COMMENT '银行账户ID',
  `rule_type` bigint NULL COMMENT '规则类型',
  `rule_value` varchar(255) NULL COMMENT '规则值',
  `priority` int NULL COMMENT '优先级',
  `status` bigint NULL COMMENT '状态',
  PRIMARY KEY (`id`)
) COMMENT='银行路由规则表' ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `xdyai_tax_rate_version` (
  `id` bigint NOT NULL COMMENT '主键',
  `created_time` datetime NULL COMMENT '创建时间',
  `updated_time` datetime NULL COMMENT '更新时间',
  `created_by` varchar(255) NULL COMMENT '创建者',
  `updated_by` varchar(255) NULL COMMENT '更新者',
  `country` varchar(64) NULL COMMENT '国家',
  `region` varchar(64) NULL COMMENT '地区',
  `tax_type` varchar(64) NULL COMMENT '税种',
  `tax_rate` decimal(8,4) NULL COMMENT '税率',
  `effective_date` date NULL COMMENT '生效日期',
  `expiry_date` date NULL COMMENT '失效日期',
  `is_default` tinyint(1) NULL COMMENT '是否默认',
  `status` bigint NULL COMMENT '状态',
  `remark` varchar(4000) NULL COMMENT '备注',
  PRIMARY KEY (`id`)
) COMMENT='税率版本表' ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `xdyai_dict_type` (
  `id` bigint NOT NULL COMMENT '主键',
  `created_time` datetime NULL COMMENT '创建时间',
  `updated_time` datetime NULL COMMENT '更新时间',
  `created_by` varchar(255) NULL COMMENT '创建者',
  `updated_by` varchar(255) NULL COMMENT '更新者',
  `code` varchar(255) NOT NULL COMMENT '字典编码',
  `name` varchar(255) NOT NULL COMMENT '字典名称',
  `status` bigint NULL COMMENT '状态',
  `remark` varchar(4000) NULL COMMENT '备注',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_dict_type_code` (`code`),
  UNIQUE KEY `uk_dict_type_name` (`name`)
) COMMENT='字典类型表' ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `xdyai_dict_item` (
  `id` bigint NOT NULL COMMENT '主键',
  `created_time` datetime NULL COMMENT '创建时间',
  `updated_time` datetime NULL COMMENT '更新时间',
  `created_by` varchar(255) NULL COMMENT '创建者',
  `updated_by` varchar(255) NULL COMMENT '更新者',
  `dict_type_id` bigint NOT NULL COMMENT '字典类型ID',
  `item_key` varchar(255) NOT NULL COMMENT '字典键',
  `item_value` varchar(255) NOT NULL COMMENT '字典值',
  `sort` int NULL COMMENT '排序',
  `status` bigint NULL COMMENT '状态',
  `remark` varchar(4000) NULL COMMENT '备注',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_dict_item_type_key` (`dict_type_id`, `item_key`)
) COMMENT='字典项表' ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
